blog:
    path:     /
    defaults: { _controller: KolomietsBlogBundle:Default:showPosts }

locale_show:
    path:     /{_locale}/show
    defaults: { _controller: KolomietsBlogBundle:Default:showPosts }
    requirements:
        _locale: en|ru

show_posts:
    path:     /show
    defaults: { _controller: KolomietsBlogBundle:Default:showPosts }

add_post:
    path:     /addpost
    defaults: { _controller: KolomietsBlogBundle:Default:addPost }

remove_post:
    path:     /remove/{postId}
    defaults: { _controller: KolomietsBlogBundle:Default:removePost, postId: '0' }
    requirements:
        postId: '\d+'

edit_post:
    path:     /edit/{postId}
    defaults: { _controller: KolomietsBlogBundle:Default:editPost, postId: '0' }
    requirements:
        postId: '\d+'

add_category:
    path:     /addcategory
    defaults: { _controller: KolomietsBlogBundle:Category:addCategory }

add_comment:
    path:     /addcomment/{postId}
    defaults: { _controller: KolomietsBlogBundle:Comment:addComment, postId: '0' }
    requirements:
        postId: '\d+'
