kolomiets_blog_homepage:
    path:     /index
    defaults: { _controller: KolomietsBlogBundle:Default:index }

kolomiets_blog_show_posts:
    path:     /show
    defaults: { _controller: KolomietsBlogBundle:Default:showPosts }
