fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

kolomiets_blog:
    resource: "@KolomietsBlogBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

blog_api:
    resource: "@KolomietsBlogBundle/Resources/config/routing_api.yml"
    prefix:   /api
