# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.menu_builder:
              class: Kolomiets\BlogBundle\Menu\MenuBuilder
              arguments: ["@knp_menu.factory"]
              tags:
                  - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
