<?php

namespace Kolomiets\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    //insert INTO post (name, text, date, author) VALUES ("Some post","Some default text in this post", "2016-12-24", 1);
    //insert INTO post (name, text, date, author) VALUES ("Second post","Some second text in this post", "2016-12-25", 2);

}
