<?php

namespace Kolomiets\BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param String $text
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findPostByText(String $text) {
        return $this->createQueryBuilder('p')
            ->where('p.name LIKE :text')
            ->orWhere('p.text LIKE :text')
            ->setParameter('text', '%'.$text.'%')
            ->getQuery()
            ->getResult();
    }

    public function findPostByCategory(Int $id) {
        return $this->createQueryBuilder('p')
            ->where('p.category = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
